### PR TITLE
Use WHOX in servers which support it

### PR DESCRIPTION
**Pull request by necessary129**
Using WHOX have many benefits. This patch will make aka use WHOX so that when the module send s a WHOX request, and gets its reply, it won't be forwarded to the client. The reply will be the normal WHO reply if the server doesn't support WHOX, so it will not break anything.

### CODE REVIEW

**Comment by emagaliff** [comment]
WHOX codes are not standard and differ across networks. `self.PutIRC("WHO {0} %thnuc,854".format(chan)` will result in different responses on different networks.

No way to ensure same data always retrieved.

**Comment by Mikaela** [comment]
https://github.com/ircv3/ircv3-specifications/issues/81 would help.

**Comment by emagaliff** [comment]
@Mikaela Thanks! I came across the second webpage that references. A adopted, set standard for WHOX would be awesome, and I'll definitely keep an eye out.

I tried to implement what @necessary129 pushed, but ran into 2 problems:
1. `WHO {0} %thnuc,854` worked wonderfully on freenode and returned exactly what I wanted: A WHO reply with a custom code (%t 854). However, some networks, such as @snoonetIRC (InspIRCd) use `%t` to mean something else, in this case "Show users connected within this number of seconds," which is clearly not what we want.
2. Eliminating the `%t,854` custom code worked just fine for when we sent `%hnuc`, but if a user sent a custom `WHOX` with different codes, it would not parse properly as the reply would not contain the data we want.

Until it's made an adopted standard, If you can think of a way to get the `WHOX` replies sent by `aka` without also parsing those sent by other means, that would be fantastic and I could add in.

**Comment by necessary129** [comment]
@emagaliff stripping `%t` won't help as if a user does `WHO #channel %n` andwhen  `aka` tries to process it, it will result with an `IndexError` so let's wait for that spec, lol

**Pull request closed without merging**
